minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin123}
  bucket: ${MINIO_BUCKET:product-files}
  presign-expire: ${MINIO_PRESIGN_EXPIRE:300}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
